### ISSUE TITLE
Limit location range to United States only

### ISSUE THREAD

**Issue by k4rni** [acmcsufoss/acmOpportunities#18]
The locations for the most recent job postings have been expanded to out of the country. While most students are open to moving out of state for job opportunities, moving out of country is less desirable.

This may require you to add a location filter or update the prompt for the PaLM api to achieve desired results.

References:
<img width="382" alt="image" src="https://github.com/acmcsufoss/acmOpportunities/assets/60043611/17cba3a5-0453-4c70-a946-8f03cdb6d5c8">

**Comment by boushrabettir** [comment]
This issue is ready to be closed when `Fix/18` is successfully merged into main branch!

**Comment by boushrabettir** [comment]
Internship opportunities still out of America. Although the link was updated it still seems the same. 
![image](https://github.com/acmcsufoss/acmOpportunities/assets/116927138/f4448551-5b7b-4a60-8049-e3f8af574355)


Possible fix is to change the location specifically to `United States` and offer internships only based in the U.S.
